### ISSUE TITLE
There has no example_train_blending.sh

### ISSUE THREAD

**Issue by aruiplex** [mlpc-ucsd/BDM#4]
Hi, I wonder how to train the prior model. I can only train the model by the `main.py`, how to use the `main_blending.py` to train the prior model?

**Comment by TheKnight-Z** [comment]
Hi @aruiplex ,

We don't provide the scripts for training prior model because It depends on which prior model you intend to train and then use. In BDM which focuses on the representation of point clouds, our prior model is based on [PVD](https://github.com/alexzhou907/PVD). We also test results on a more "powerful" prior model [DiT-3D](https://github.com/DiT-3D/). We suggest you refering to many powerful prior models nowadays.

Good luck!

**Comment by aruiplex** [comment]
Hi, I want to reproduce your experiments, could you provide the airplane and car PVD checkpoints? I tried to train them, but it seems to use too much computation. It is another kind of "Slow-science" 🤣. It will consume 2 RTX3090 to train 6 days. 

Very thanks for your response.

**Comment by aruiplex** [comment]
@TheKnight-Z Thank you

**Comment by TheKnight-Z** [comment]
Sorry for the late response. We provide the PVD checkpoints [here](https://drive.google.com/drive/folders/1gX6eIqkP3-MXI5XOcSKlKzOMJNulTp-P?usp=sharing), including airplane, car, sofa and table.

**Comment by aruiplex** [comment]
Got it, god bless you for your research.
